---
- name: pypi | Install required packages from Pypi
  ansible.builtin.pip:
    name: ara[server]
    state: "{{ (ara_api_version == 'latest') | ternary('latest', 'present') }}"
    version: "{{ (ara_api_version != 'latest') | ternary(ara_api_version, omit) }}"
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    virtualenv_command: /usr/bin/python3 -m venv
  notify: Restart ara-api

- name: pypi | Install python-passlib for managing authentication credentials
  ansible.builtin.pip:
    name: passlib
    state: present
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    virtualenv_command: /usr/bin/python3 -m venv
  when: ara_api_external_auth

- name: pypi | Prefix the virtualenv bin directory to PATH
  ansible.builtin.set_fact:
    path_with_virtualenv: "{{ ara_api_venv_path }}/bin:{{ ansible_facts['env']['PATH'] }}"
  when: ara_api_venv | bool
