---
# This ensures the WSGI application servers are set up to use the right endpoint
- name: Set WSGI application to distributed_sqlite
  ansible.builtin.set_fact:
    _ara_api_wsgi_application: "ara.server.wsgi:distributed_sqlite"
