---
- name: database_engine | django.db.backends.sqlite3 | Ensure the database directory exists
  ansible.builtin.file:
    path: "{{ ara_api_database_name | dirname }}"
    state: directory
    mode: "0750"

- name: database_engine | django.db.backends.sqlite3 | Run SQL migrations
  environment:
    ARA_SETTINGS: "{{ ara_api_settings }}"
    PATH: "{{ path_with_virtualenv }}"
  ansible.builtin.command: ara-manage migrate
  run_once: true
  register: _ara_sql_migrations
  retries: 3
  delay: 5
  until: _ara_sql_migrations is succeeded
  changed_when: '"No migrations to apply" not in _ara_sql_migrations.stdout'
