---
- name: Restart ara-api
  become: true
  ansible.builtin.service:
    name: ara-api
    state: restarted
  when:
    - ara_api_wsgi_server is not none
    - ara_api_service_enabled is not changed
